version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      gradle-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/tools/generate-compliance-tests"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      gomod-dependencies:
        patterns:
          - "*"
